name: Test servers
on:
  workflow_dispatch:
  workflow_call:
  push:
  pull_request:

jobs:
  run:
    strategy:
      matrix:
        version:
          - { mc: 1.21.5, type: vanilla, java: 21 }
          - { mc: 1.21.5, type: paper, java: 21 }
          - { mc: 1.21.5, type: forge, java: 21 }
          - { mc: 1.21.5, type: neoforge, java: 21 }
          - { mc: 1.21.5, type: fabric, java: 21 }
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v4
      - name: Run server
        timeout-minutes: 3
        uses: ./
        with:
          mc: ${{ matrix.version.mc }}
          modloader: ${{ matrix.version.type }}
          java: ${{ matrix.version.java }}
